### ISSUE TITLE
data and readme file

### ISSUE THREAD

**Issue by dshizuka** [fhuang0226/BIOS967_Huang#1]
Hi Fan, I've looked at your data and readme file. A couple of notes:
- for your readme file, please include an explanation of what the values in the cells are. Are the expression levels? I'm not sure.
- for your column names, are the numbers after the dash indicating the sample (i.e., "Day0-1" = plant #1)? And if so, are samples with the same number coming from the same plant? 
- it looks like your data is a subset of data? Or is it that you are still in the middle of collecting data? If it's a subset, you could go ahead and delete all of the GeneIDs that are not used. Otherwise, you'll create a bunch of NAs that don't need to be there. 
- finally, your data will likely need to be reformatted in order to do any visualizations or analysis. "Day" and "Sample" should be variables (separate columns), and "gene ID" and "value" (expression level, or whatever these values represent) should probably separate variables too? We can work more on this as you move forward on the project.

**Comment by fhuang0226** [comment]
Hi, Dr Shizuka,

Thank you for your suggestions. That's the data I would like to use for my project. I will modify them and write the explanation again.

Fan
